# Generated by Django 4.2 on 2023-10-17 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flashcard_app', '0002_alter_dictionary_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='source',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
