# Generated by Django 4.2 on 2023-10-17 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard_app', '0003_dictionary_user_alter_dictionary_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
