# Generated by Django 4.2 on 2023-12-27 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard_app', '0005_dictionary_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
