# Generated by Django 4.2 on 2024-01-25 02:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard_app', '0007_alter_dictionary_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])]),
        ),
    ]
